### ISSUE TITLE
Problems using import

### ISSUE THREAD

**Issue by luixal** [icastillejogomez/degiro-api#46] opened 2022-12-28 12:37 UTC
Hi,

I just got started with DeGiro and this package... and I'm having some problems when using import:

If I try this code:

```js
import DeGiro from "degiro-api";

const username = 'myUsername';
const password = 'myPassword';

const degiro = new DeGiro({ username, password });
```

I just got the following error:

```
TypeError: DeGiro is not a constructor
```

If I opt to use the `create` function, like this:

```js
const degiro = DeGiro.create({username, password});
```

I got this error:

```
TypeError: DeGiro.create is not a function
```

I've tried the same code using Node 16.x and 18.x, any idea of what can be the problem?

Thanks for your work!

**Comment by danielvandenberg95** [comment] 2022-12-29 07:41
Hi luixal,

In your other question I see you got this to work with require. As such, I'm assuming this is a problem with your build setup, not with this project. To confirm the issue is not in this project, could you try importing any other project?

**Comment by luixal** [comment] 2022-12-29 10:56
Hi,

I don't have this issue in other projects. Just for testing, I've added lodash to the project where I'm trying to use this package and I can import an use lodash without any problems.

Don't think it's a problem with my setup. Can you point me in a direction to find out what's happening?

Thanks!

**Comment by j-a-m-l** [comment] 2023-02-16 13:45
@luixal try:
```ts
import degiroApi from 'degiro-api'
const DeGiro = (degiroApi as any).default
````

**Comment by yarcheek** [comment] 2023-02-20 15:46
@luixal or try this

```
import degiroApi from 'degiro-api';
const DeGiro = (degiroApi).default;
```

**Comment by luixal** [comment] 2023-02-23 17:12
Thanks @j-a-m-l and @yarcheek , that did work.

No idea why it is needed, but that **should totally appear** in the readme's example.

**Comment by icastillejogomez** [comment] 2023-06-05 10:37
Close this from now. This repository is open to accept pull requests if you would to achieve that natively

**Closed as completed by icastillejogomez** 2023-06-05 10:37 UTC
